### ISSUE TITLE
Really can't wait! Please update SpiralPullToRefresh iOS7 support.

### ISSUE THREAD

**Issue by iebox** [kronik/SpiralPullToRefresh#6]

**Comment by kronik** [comment]
Done. Good luck!

**Comment by iebox** [comment]
sorry,  it’s not working with the navigation bar.
the location still wrong.

sorry to bother, but we really love this effect.

please do help us fix it.

thank you very much!

Mike
